usr/include/kysdk/kysdk-system/libkync.h
usr/include/kysdk/kysdk-system/libkycpu.h
usr/include/kysdk/kysdk-system/libkyprinter.h
usr/include/kysdk/kysdk-system/libkybios.h
usr/include/kysdk/kysdk-system/libkyboard.h
usr/include/kysdk/kysdk-system/libkyusb.h
usr/include/kysdk/kysdk-system/libkybluetooth.h
usr/include/kysdk/kysdk-system/libkydisplay.h
usr/include/kysdk/kysdk-system/libkyedid.h
usr/include/kysdk/kysdk-system/libkyfan.h
usr/include/kysdk/kysdk-system/libkyhw.h
development-files/kysdk-hardware.pc usr/share/pkgconfig/
