#ifndef FILEWATCHER_GLOBAL_H
#define FILEWATCHER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEWATCHER_LIBRARY)
#  define FILEWATCHER_EXPORT Q_DECL_EXPORT
#else
#  define FILEWATCHER_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEWATCHER_GLOBAL_H
